### PR TITLE
axios call, input field events tied to call

### PR DESCRIPTION
**Pull request by BrakeLJ**
- Added constructor and super() to both App.js and Body.js
- Created state in Body.js 'artist' and 'song'
- created onChange events that store user input into artist/song state
- created event on button to make axios call using artist/song state.
- call is successful. console.log results works. However, ran into an issue where sometimes the lyrics are returned in the data object that is logged and sometimes they are not using the same call.

### CODE REVIEW

**Review by RyanTjong88 — APPROVED** [review]
Great work Lucas! I would suggest adding onSubmit={this.getLyrics} to the form on line 43 in App.js on remove onClick={this.getLyrics} on line 60 for accessibility reasons. BUT is just a suggestion.

**Review by karinavertti — APPROVED** [review]
Great work Lucas! Thank you.

**Comment by inthehouseofleaves** [comment]
Looks great! Putting everything on its own line improves readability. Good job!

**Review by inthehouseofleaves — APPROVED** [review]
Readability is great! Thanks a bunch for improving

**Pull request merged**
