### PR TITLE
header component

### PR DESCRIPTION
**Pull request by BrakeLJ**
-Created a Header component with the title of the website.
-Added missing { Component } the the App.js file on line 1 in the initial React import

### CODE REVIEW

**Comment by RyanTjong88** [comment]
Great header!!!

**Review by karinavertti — COMMENTED** [review]
Love it!

**Comment by inthehouseofleaves** [comment]
hey! looks great

**Review by karinavertti — APPROVED** [review]

**Review by RyanTjong88 — APPROVED** [review]
go for it!

**Pull request merged**
